# Generated by Django 3.0.2 on 2020-02-04 19:49

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Article')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('discount', models.BooleanField(blank=True)),
                ('sertificate', models.BooleanField(blank=True, default=False)),
                ('sizes', models.TextField(blank=True, default='..X..', max_length=400)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='Price')),
                ('color', models.CharField(default='gray', max_length=100)),
                ('depth', models.CharField(blank=True, max_length=15)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='', verbose_name='Photo')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('body', models.TextField(max_length=500, null=True)),
                ('changed', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Page'),
        ),
    ]
