# Generated by Django 3.0.2 on 2020-01-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.IntegerField()),
                ('discount', models.BooleanField(blank=True)),
            ],
        ),
    ]
