# Generated by Django 3.0.2 on 2020-05-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcard',
            options={'ordering': ['-position'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='productcard',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция товара'),
        ),
    ]
