# Generated by Django 3.0.2 on 2020-01-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='image',
        ),
    ]
