# Generated by Django 3.0.2 on 2020-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Заголовок', max_length=100, verbose_name='Title'),
        ),
    ]
