# Generated by Django 3.0.2 on 2020-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='oldPrice',
            field=models.BooleanField(default=False, verbose_name='Только одна цена может быть старой'),
        ),
    ]
