# Generated by Django 3.0.2 on 2020-01-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200112_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='prices',
        ),
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard'),
        ),
    ]
