# Generated by Django 3.0.2 on 2020-02-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_depthprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthprice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard'),
        ),
    ]
