# Generated by Django 3.0.2 on 2020-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200506_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='position',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Позиция товара в списке товаров'),
        ),
    ]
