# Generated by Django 3.0.2 on 2020-02-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200215_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='oldPrice',
            field=models.IntegerField(null=True, verbose_name='Старая цена'),
        ),
    ]
