# Generated by Django 3.0.2 on 2020-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prices_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Тип продукта(не изменять)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Заголовок', max_length=100, verbose_name='Заголовок'),
        ),
    ]
