# Generated by Django 3.0.2 on 2020-01-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200114_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductCard', to_field='name'),
        ),
    ]
