# Generated by Django 3.0.2 on 2020-03-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200301_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposition',
            options={'verbose_name': 'Нашу работу', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AddField(
            model_name='exposition',
            name='category',
            field=models.CharField(choices=[('sett', 'Тротуарка'), ('brick', 'Блок и кирпич'), ('fence', 'Забор'), ('parapet', 'Крышки и парапеты'), ('monuments', 'Памятники')], default='trotuarka', help_text='Категория', max_length=10, unique=True),
        ),
    ]
