# Generated by Django 3.0.2 on 2020-02-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200215_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depthprice',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='depthprice',
            name='product',
        ),
        migrations.AddField(
            model_name='prices',
            name='depthPrice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.DepthPrice'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='oldPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
    ]
