# Generated by Django 3.0.2 on 2020-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200112_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='prices',
        ),
        migrations.AddField(
            model_name='productcard',
            name='prices',
            field=models.ManyToManyField(null=True, to='products.Prices'),
        ),
    ]
