# Generated by Django 3.0.2 on 2020-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_servicepage_serviceprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprices',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprices',
            name='price',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
