# Generated by Django 3.0.2 on 2020-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200301_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposition',
            old_name='title',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='exposition',
            name='category',
            field=models.CharField(choices=[('sett', 'Тротуарка'), ('brick', 'Блок и кирпич'), ('fence', 'Забор'), ('parapet', 'Крышки и парапеты'), ('monuments', 'Памятники')], default='trotuarka', help_text='Категория', max_length=10),
        ),
    ]
