# Generated by Django 3.0.2 on 2020-05-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200506_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('docFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'verbose_name': 'Нашу услугу', 'verbose_name_plural': 'Наши услуги'},
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
