# Generated by Django 3.0.2 on 2020-03-15 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200301_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Description', to=settings.AUTH_USER_MODEL),
        ),
    ]
