# Generated by Django 3.0.2 on 2020-02-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200215_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='depthPrice',
        ),
        migrations.AddField(
            model_name='prices',
            name='depthPrice',
            field=models.ManyToManyField(to='products.DepthPrice'),
        ),
    ]
