# Generated by Django 3.0.2 on 2020-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcard_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-changed']},
        ),
        migrations.AlterField(
            model_name='news',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
