# Generated by Django 3.0.2 on 2020-01-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200114_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='priceName',
        ),
        migrations.AddField(
            model_name='prices',
            name='color',
            field=models.CharField(default='gray', max_length=100),
        ),
        migrations.AddField(
            model_name='prices',
            name='depth',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
