# Generated by Django 3.0.2 on 2020-01-12 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200112_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='prices',
        ),
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCard'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(blank=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
