# Generated by Django 3.0.2 on 2020-02-15 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200215_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='depthPrice',
        ),
        migrations.AddField(
            model_name='depthprice',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Prices'),
        ),
    ]
