# Generated by Django 3.0.2 on 2020-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200120_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='sizes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
