# Generated by Django 3.0.2 on 2020-04-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200415_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depth',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depthprice',
            name='price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='exposition',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expositionphotos',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Article', verbose_name='sett=Тротуарка, fence=Забор,             brick=Кирпич, monuments=Памятники'),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='sizes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
