# Generated by Django 3.0.2 on 2020-01-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200112_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='price',
        ),
    ]
