# Generated by Django 3.0.2 on 2020-01-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productcard_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='sizes',
            field=models.TextField(blank=True, default='..X..', max_length=400),
        ),
    ]
