# Generated by Django 3.0.2 on 2020-05-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200428_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='color',
            field=models.CharField(default='Серый', max_length=100),
        ),
    ]
