# Generated by Django 3.0.2 on 2020-01-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200123_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='sertificate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
