# Generated by Django 3.0.2 on 2020-02-16 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200215_1929'),
        ('products', '0004_auto_20200206_2022'),
    ]

    operations = [
    ]
