# Generated by Django 3.0.2 on 2020-01-26 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcard_sertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
